CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "email" varchar UNIQUE,
  "senha_hash" varchar,
  "criado_em" timestamp
);

CREATE TABLE "clientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "email" varchar,
  "telefone" varchar,
  "data_cadastro" date
);

CREATE TABLE "atendimentos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "data" timestamp,
  "descricao" text
);

CREATE TABLE "feedbacks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "nota_nps" int,
  "comentario" text,
  "data" date
);

CREATE TABLE "churn_predict" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "risco_churn" decimal,
  "modelo_usado" varchar,
  "data_prevista" date
);

ALTER TABLE "atendimentos" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");

ALTER TABLE "feedbacks" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");

ALTER TABLE "churn_predict" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id");
